version: '3.8'

services:
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    runtime: nvidia
